### PR TITLE
ignore IMAGETYP and DISPERS in command line mode to support files wit…

### PR DESCRIPTION
**Pull request by 2ichard**
…h no KOA keywords

In command line mode, dispersion mode (high or low) is determined solely from echelle angle, ECHLPOS > 100 implies low-dispersion mode.  Flat is identified solely from CALMPOS = 1 for flat.

### CODE REVIEW

**Comment by Astrodude11** [comment]
@2ichard Confirmed that order of object and flat image are not critical. 

For pair subtraction in command line mode I received the message "KeyError: Keyword 'DISPERSE' not found" (same as Greg originally reported) after issuing the command:

`nsdrp.py feb18s0342.fits feb18s0301.fits -b feb18s0302.fits`

These are non-KOA files and do not have the DISPERS keyword. Looks this message is being generated on line 159 in create_raw_data_sets.py:

`if header['DISPERS'].lower() != high:`

**Comment by 2ichard** [comment]
Please confirm that you're using the version of create_raw_data_sets.py on the 0.9.16 branch (commit 894b9cf).  In that version, line 159 is:  if header['NAXIS1'] != constants.N_COLS:.

**Comment by Astrodude11** [comment]
I'm using 0.9.16 but meant line 156.

**Comment by 2ichard** [comment]
Would you send me feb18s0342.fits, feb18s0301.fits and feb18s0302.fits  so I can debug with those files?  Thanks!

**Comment by Astrodude11** [comment]
I came across an issue running 0.9.16 in KOA mode. The stack trace is attached. The issue occurred for 20170410 and the given test data, 20100429. 

nsdrp-0 9 16

**Comment by Astrodude11** [comment]
In regard to my previous comment, is there a benefit to importing nirspec_constants as two different aliases? In GratingEq and create_raw_data_sets it is imported as const and as constants, respectively. 

Per the issue I reported, create_raw_data_sets calls constants.filter_names but the list filter_names is not in nirspec_constants.

`if header['FILNAME'].upper() not in constants.filter_names:`
`    failed2reduce['fil'] += 1`
`    return False`

whereas in the previous version of the code this is accomplished by:

`if header['FILNAME'].lower().find('nirspec') < 0:`
 `    return False`

In my local copy of 0.9.16 I changed the code to use .find() and everything processed normally. Correct me if I'm wrong, but the .find() approach was removed to prevent finding concatenated filters like "m-widenirspec-7", right? We could avoid the problem of concatenated filters and eradicate the need to create/import a list (e.g. constants.filter_names) if we use a regular expression in a condition like:

`import re`

`filter_names = re.compile('nirspec-([\d]|[a][o])') # satisfies nirspec-[1-7] and nirspec-ao`
`if not filter_names.search(header['FILNAME'].lower()):`
`return False`

I made this change to my local copy of 0.9.16 and NSDRP runs as expected on the given 20100429 test data. However, regardless of a list, .find(), or a regular expression, I receive the following error for 20170410 data:

error

The -verbose mode shows that this error occurs while trying to create data products for NS.20170408.28848.fits and NS.20170410.30626. The log for each file reports "frame A top background window width = 0."

**Comment by Astrodude11** [comment]
@2ichard Anastasia and I noticed an inconsistency in the naming convention of data product filenames. Specifically FITS tables, they followed the koaid_type_order style where type is flux/profile/etc e.g. NS.20100429.40280_flux_43_tbl.fits.  All other files followed the koaid_order_type convention such as NS.20100429.40280_43_flux.txt. To keep the filenames consistent I propose we change line 72 in products.py from
`return fn[:fn.rfind('_') + 1] + str(order) + fn[fn.rfind('_'):]`
to
`return fn[:fn.rfind(base_name) + len(base_name) + 1] + str(order) + fn[fn.rfind(fn_suffix)-1:]`

I tested this change in my local copy of 0.9.16 and the filenames are consistent. See the attached folder.

[20100429.zip](https://github.com/Keck-DataReductionPipelines/NIRSPEC-Data-Reduction-Pipeline/files/926332/20100429.zip)

**Comment by 2ichard** [comment]
@Astrodude11 I see how this error (inconsistency) was introduced with the change to FITS table names and I agree with your proposed change.  Would you please add this commit to the 0.9.16 branch?

**Comment by Astrodude11** [comment]
Verified consistent data product filenames, NSDRPVER keyword, and pair subtraction commits work as expected. 

To do: add filter names list to nirspec_constants.py, remove multiple aliases to nirspec_constants, SKYDIST index error.

**Comment by 2ichard** [comment]
@Astrodude11 A slightly more pythonic way of doing it would be: 

if obj_header['FILNAME'].upper() not in nirspec_constants.filter_names:

Do you agree?  Both methods amount to the exact same thing but the "not in" construct seems more human readable to me and it doesn't require the reader to realize that index() returns -1 if the value is not in the list.

The upper() may not be necessary though it does no harm.

**Pull request merged**
